version: 2

project_name: clean-mvn

builds:
  - id: clean-mvn
    main: ./main.go
    binary: clean-mvn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    files:
      - "**/*"        # 首先包含所有文件
      - "!img/**"     # 然后排除整个 img 目录及其所有内容

archives:
  - id: default
    builds:
      - clean-mvn
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-SHA256SUMS.txt"
  algorithm: sha256
